site_name: Phoenix BSL
nav:
  - Домашняя: index.md
  - Руководство контрибьютора: contributing/index.md
  - English: https://otymko.github.io/phoenixbsl/en
theme: 
  name: material
  language: ru
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.png'
  palette:
    primary: 'white'
    accent: 'indigo'
extra:
  search:
    language: 'en, ru'
  social:
    - type: 'github'
      link: 'https://github.com/otymko'
extra_css:
  - 'assets/stylesheets/extra.css'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

site_url: 'https://otymko.github.io/phoenixbsl'
repo_name: 'otymko/phoenixbsl'
repo_url: 'https://github.com/otymko/phoenixbsl'
edit_uri: 'edit/develop/docs'