name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            displayName: Windows
            prefix: win
            jpackageDownload: https://download.java.net/java/early_access/jdk14/27/GPL/openjdk-14-ea+27_windows-x64_bin.zip
            jdk14Path: /jdk-14
    runs-on: ${{ matrix.os }}
    name: Create app image

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Install python lib requests
      run: pip install requests  
    - name: Download jpackage
        # We need to download jpackage from https://jdk.java.net/jpackage/
      run: |
          import tarfile
          import zipfile
          import sys
          if sys.version_info[0] >= 3:
            from urllib.request import urlretrieve
          else:
            from urllib import urlretrieve
          url = "${{ matrix.jpackageDownload }}"
          tmpfile, headers = urlretrieve(url)
          if (url.endswith("tar.gz")):
            tar = tarfile.open(tmpfile)
            tar.extractall()
            tar.close()
          elif (url.endswith("zip")):
            zip = zipfile.ZipFile(tmpfile)
            zip.extractall()
            zip.close()
      shell: python
    - name: Build jpackage msi
      run: ./gradlew jpackage
      env:
        JPACKAGE_HOME: "${{ matrix.jdk14Path }}/bin/jpackage.exe"
    - uses: actions/upload-artifact@master
      with:
        name: phoenixbsl.msi
        path: ./phoenixbsl-0.3.1.msi
